### ISSUE TITLE
tinkoff-payment

### ISSUE THREAD

**Issue by yeoncis** [YosaRem/numeth#1]
Здравствуй!
Не нашел контакты у тебя тут, поэтому пишу тут.. Надеюсь ты не будешь расстраиваться :3

Я сохранил твой проект tinkoff-payment в закладках в качестве источника вдохновения с интересными для меня вещами. Точно не помню за что я сохранил, но таких закладок немного. Сейчас же, планируя свое приложение я столкнулся с проблемой, что ты скрыл/удалил его...

Не мог бы ты вновь поделиться им?)

**Comment by YosaRem** [comment]
@yeoncis 
Привет. 
Вообще говоря, в том репозитории не полностью готовое приложение было, потому и скрыл его. 
До ума оно довелось только один раз, во время интеграции этой штуки на прод. 

Если сильно нужно, то можешь написать сюда ilya.solomein@gmail.com . Дам доступ к репозиторию. Возвращать его в публичные не хочу.
